'use strict';
window.RVU_CLARITY_PROJECT_ID='ydzz6gt587';
window.clarity=window.clarity||function(){(window.clarity.q=window.clarity.q||[]).push(arguments);};
(function(){const s=document.createElement('script');s.async=true;s.src='https://www.clarity.ms/tag/'+window.RVU_CLARITY_PROJECT_ID;s.referrerPolicy='no-referrer';document.head.appendChild(s);})();
(function(){
const root=document.documentElement;
const langToggle=document.getElementById('langToggle');
let lang='ar';
try{const saved=localStorage.getItem('rvuLang');if(saved==='en'||saved==='ar')lang=saved;}catch(e){}
function applyLanguage(next){lang=next;window.RVU_LANG=lang;root.lang=lang;root.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('.i18n').forEach(el=>{const value=el.dataset[lang];if(value!==undefined)el.textContent=value;});if(langToggle){langToggle.textContent=lang==='ar'?'EN':'AR';langToggle.setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');}const name=document.getElementById('appName');const goal=document.getElementById('appGoal');const close=document.getElementById('applicationClose');if(name)name.placeholder=lang==='ar'?'مثال: أحمد محمد':'e.g. Ahmed Mohamed';if(goal)goal.placeholder=lang==='ar'?'إيه اللي موقفك دلوقتي وإيه اللي عاوز توصله؟':'What is blocking you now and what do you want to achieve?';if(close)close.setAttribute('aria-label',lang==='ar'?'إغلاق نموذج التقديم':'Close application form');try{localStorage.setItem('rvuLang',lang);}catch(e){}}
if(langToggle)langToggle.addEventListener('click',()=>applyLanguage(lang==='ar'?'en':'ar'));
applyLanguage(lang);
document.querySelectorAll('.week-toggle').forEach(button=>{button.addEventListener('click',()=>{const panel=button.nextElementSibling;const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));if(panel)panel.hidden=open;const icon=button.querySelector('.week-icon');if(icon)icon.textContent=open?'+':'−';});});
document.querySelectorAll('.faq-question').forEach(button=>{button.addEventListener('click',()=>{const answer=button.nextElementSibling;const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));if(answer)answer.hidden=open;const icon=button.lastElementChild;if(icon)icon.textContent=open?'+':'−';});});
const lightbox=document.getElementById('pocLightbox');const lightboxImage=document.getElementById('pocLightboxImage');const lightboxClose=document.getElementById('pocLightboxClose');let lastPocTrigger=null;
function closeLightbox(){if(!lightbox)return;lightbox.classList.remove('show');lightbox.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(lightboxImage)lightboxImage.removeAttribute('src');if(lastPocTrigger)lastPocTrigger.focus();}
document.querySelectorAll('[data-poc]').forEach(button=>{button.addEventListener('click',()=>{if(!lightbox||!lightboxImage)return;lastPocTrigger=button;lightboxImage.src=button.dataset.poc;lightbox.classList.add('show');lightbox.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');if(lightboxClose)lightboxClose.focus();});});
if(lightboxClose)lightboxClose.addEventListener('click',closeLightbox);
if(lightbox)lightbox.addEventListener('click',event=>{if(event.target===lightbox)closeLightbox();});
const modal=document.getElementById('applicationModal');const closeButton=document.getElementById('applicationClose');const form=document.getElementById('applicationForm');const success=document.getElementById('applicationSuccess');const summary=document.getElementById('applicationSummary');const waLink=document.getElementById('applicationWhatsApp');const editButton=document.getElementById('applicationEdit');let lastApplicationTrigger=null;
function openApplication(trigger){if(!modal)return;lastApplicationTrigger=trigger||document.activeElement;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');requestAnimationFrame(()=>{const name=document.getElementById('appName');if(name&&form&&!form.hidden)name.focus();else if(closeButton)closeButton.focus();});}
function closeApplication(){if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(lastApplicationTrigger&&typeof lastApplicationTrigger.focus==='function')lastApplicationTrigger.focus();}
document.querySelectorAll('[data-open-application]').forEach(button=>button.addEventListener('click',()=>openApplication(button)));
if(closeButton)closeButton.addEventListener('click',closeApplication);
if(modal)modal.addEventListener('click',event=>{if(event.target===modal)closeApplication();});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(modal&&modal.classList.contains('show'))closeApplication();else if(lightbox&&lightbox.classList.contains('show'))closeLightbox();});
if(form){form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const name=document.getElementById('appName').value.trim();const level=document.getElementById('appLevel').value;const live=document.getElementById('appLiveTargets').value;const goal=document.getElementById('appGoal').value.trim();const textAr=`طلب تقديم — rv_u Mentorship Camp\nالاسم: ${name}\nالمستوى: ${level}\nاشتغلت على Live Targets: ${live}\nالهدف: ${goal}`;const textEn=`Application — rv_u Mentorship Camp\nName: ${name}\nLevel: ${level}\nLive Targets: ${live}\nGoal: ${goal}`;const message=lang==='ar'?textAr:textEn;if(summary)summary.textContent=message;if(waLink){const url=new URL('https://wa.me/201280499854');url.searchParams.set('text',message);waLink.href=url.href;}form.hidden=true;if(success)success.hidden=false;if(closeButton)closeButton.focus();if(window.clarity)window.clarity('event','application_ready');});}
if(editButton)editButton.addEventListener('click',()=>{if(success)success.hidden=true;if(form)form.hidden=false;const name=document.getElementById('appName');if(name)name.focus();});
if(waLink)waLink.addEventListener('click',()=>{if(window.clarity)window.clarity('event','application_whatsapp');});
const mobileApply=document.getElementById('mobileApply');const hero=document.getElementById('top');const apply=document.getElementById('apply');
function updateMobileApply(){if(!mobileApply||window.innerWidth>720)return;const heroRect=hero?hero.getBoundingClientRect():null;const applyRect=apply?apply.getBoundingClientRect():null;const heroVisible=heroRect&&heroRect.bottom>110;const applyVisible=applyRect&&applyRect.top<window.innerHeight*.86&&applyRect.bottom>0;const shouldShow=!heroVisible&&!applyVisible&&!(modal&&modal.classList.contains('show'));mobileApply.classList.toggle('show',shouldShow);}
updateMobileApply();window.addEventListener('scroll',updateMobileApply,{passive:true});window.addEventListener('resize',updateMobileApply,{passive:true});
})();
